# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: '$(dockerId).azurecr.io/hemaratings-submitter'

steps:
- task: DockerCompose@0
  inputs:
    dockerComposeFile: 'docker-compose.yml'
    action: 'build Services'
    dockerComposeFileArgs: REDIS_URI=redis://redis:6379
  displayName: 'Compose build'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    docker tag hemaratingssubmit  $(imageName):latest
    docker push $(imageName)
    
  displayName: 'Publish to Azure Container Registry'

    