version: '2'

services:
    backend:
        environment:
            REDIS_URI: $REDIS_URI
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - ./backend:/opt/app/backend
            - ./config/dev/nginx.conf:/etc/nginx/sites-enabled/default
        ports:
            - 8000:80
        command: "/opt/app/backend/scripts/init.sh"

    redis:
        image: redis:latest
        expose:
          - "6379"
